### ISSUE TITLE
Table of Contents (TOC) in parsa latex template

### ISSUE THREAD

**Issue by mohammaddmt** [farshadrasuli/parsa#1]
Dear Dr. Rasuli
I have a question from you, I can't see the table of contents and/or table of figures in my parsa template file (نمونه قالب لاتک پایان نامه برای تمام دانشگاه ها). is there a problem with my file?
Could you please help me in this regard?
Thanks
Mohammad

**Comment by farshadrasuli** [comment]
Hello dear Mohammad
You can use <\tableofcontents> command for TOC. Also you can use <\listoffigures> and <\listoftables> commands for TOF and TOT, respectively, everywhere you want. I'll put this tables in next version. And finally, I'm a master's degree student, not doctor. Good luck

**Comment by mohammaddmt** [comment]
Thank you so much for your reply Mr. rasuli 
I hope you the best in your career.
BR 
Mohammad

**Comment by mohammaddmt** [comment]
Thank you for your email!
