### ISSUE TITLE
Can't typeset tex files with the latest LiveTex update

### ISSUE THREAD

**Issue by moghaddamhreza** [farshadrasuli/parsa#2]
Hi Dear Farshad,
I Can't typset your Latest "نمونه قالب پایان نامه خام برای تمام دانشگاه ها.rar" 08Feb2020 files with the latest LiveTex update.

p.s: log file attached
[minimaltemplate.log](https://github.com/farshadrasuli/parsa/files/4237916/minimaltemplate.log)

**Comment by farshadrasuli** [comment]
Hi Dear Reza,
I can't find out your problem is; I wish I could help you.

**Comment by moghaddamhreza** [comment]
Problem solved by this command:
`fmtutil-sys --all`
