### ISSUE TITLE
تشکر

### ISSUE THREAD

**Issue by nasiraeemohammad** [farshadrasuli/parsa#3]

**Comment by farshadrasuli** [comment]
http://qa.parsilatex.com/37955/%D9%81%D8%A7%D8%B5%D9%84%D9%87-%D8%A8%DB%8C%D9%86-%D8%B9%D8%AF%D8%AF-%D9%BE%D8%A7%D9%86%D9%88%D8%B4%D8%AA-%D8%A8%D8%A7-%DA%A9%D9%84%D9%85%D9%87-%D9%85%D8%AF-%D9%86%D8%B8%D8%B1?show=37956#a37956
